[package]
name = "testr-cli"

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
testrepository_repository.workspace = true
